# Generated by Django 6.0.1 on 2026-01-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='date_envoi',
        ),
    ]
